# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-05-10 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appserver', '0002_tag_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(default='TODO', max_length=100),
        ),
    ]
