# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-05-10 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appserver', '0003_task_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='parent_tag',
            new_name='parent_task',
        ),
    ]
